SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX IX_Activity_tbAttribute ON Activity.tbAttribute
(
	Attribute ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Activity_tbAttribute_DefaultText ON Activity.tbAttribute
(
	DefaultText ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Activity_tbAttribute_OrderBy ON Activity.tbAttribute
(
	ActivityCode ASC,
	PrintOrder ASC,
	Attribute ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Activity_tbAttribute_Type_OrderBy ON Activity.tbAttribute
(
	ActivityCode ASC,
	AttributeTypeCode ASC,
	PrintOrder ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IDX_ChildCodeParentCode ON Activity.tbFlow
(
	ChildCode ASC,
	ParentCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IDX_ParentCodeChildCode ON Activity.tbFlow
(
	ParentCode ASC,
	ChildCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Activity_tbOp_Operation ON Activity.tbOp
(
	Operation ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Cash_tbCategory_DisplayOrder ON Cash.tbCategory
(
	DisplayOrder ASC,
	Category ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Cash_tbCategory_Name ON Cash.tbCategory
(
	Category ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Cash_tbCategory_TypeCategory ON Cash.tbCategory
(
	CategoryTypeCode ASC,
	Category ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Cash_tbCategory_TypeOrderCategory ON Cash.tbCategory
(
	CategoryTypeCode ASC,
	DisplayOrder ASC,
	Category ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Invoice_tb_AccountCode ON Invoice.tbInvoice
(
	AccountCode ASC,
	InvoicedOn ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX IX_Invoice_tb_Status ON Invoice.tbInvoice
(
	InvoiceStatusCode ASC,
	InvoicedOn ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Invoice_tb_UserId ON Invoice.tbInvoice
(
	UserId ASC,
	InvoiceNumber ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Invoice_tbItem_CashCode ON Invoice.tbItem
(
	CashCode ASC,
	InvoiceNumber ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Invoice_tbTask_CashCode ON Invoice.tbTask
(
	CashCode ASC,
	InvoiceNumber ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Invoice_tbTask_TaskCode ON Invoice.tbTask
(
	TaskCode ASC,
	InvoiceNumber ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE UNIQUE NONCLUSTERED INDEX IX_Org_tb_AccountName ON Org.tbOrg
(
	AccountName ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Org_tb_AccountSource ON Org.tbOrg
(
	AccountSource ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Org_tb_AreaCode ON Org.tbOrg
(
	AreaCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Org_tb_IndustrySector ON Org.tbOrg
(
	IndustrySector ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX IX_Org_tb_OrganisationStatusCode ON Org.tbOrg
(
	OrganisationStatusCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE UNIQUE NONCLUSTERED INDEX IX_Org_tb_OrganisationStatusCodeAccountCode ON Org.tbOrg
(
	OrganisationStatusCode ASC,
	AccountName ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX IX_Org_tb_OrganisationTypeCode ON Org.tbOrg
(
	OrganisationTypeCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Org_tb_PaymentTerms ON Org.tbOrg
(
	PaymentTerms ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE UNIQUE NONCLUSTERED INDEX IX_Org_tbAccount ON Org.tbAccount
(
	AccountCode ASC,
	CashAccountCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE UNIQUE NONCLUSTERED INDEX IX_Org_tbAddress ON Org.tbAddress
(
	AccountCode ASC,
	AddressCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Org_tbContactDepartment ON Org.tbContact
(
	Department ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Org_tbContactJobTitle ON Org.tbContact
(
	JobTitle ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Org_tbContactNameTitle ON Org.tbContact
(
	NameTitle ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX tbOrgtbOrgContact ON Org.tbContact
(
	AccountCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE UNIQUE NONCLUSTERED INDEX DocumentName ON Org.tbDoc
(
	DocumentName ASC,
	AccountCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX tbOrgtbOrgDoc ON Org.tbDoc
(
	AccountCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Org_tbPayment ON Org.tbPayment
(
	PaymentReference ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Org_tbPayment_AccountCode ON Org.tbPayment
(
	AccountCode ASC,
	PaidOn DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Org_tbPayment_CashAccountCode ON Org.tbPayment
(
	CashAccountCode ASC,
	PaidOn ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Org_tbPayment_CashCode ON Org.tbPayment
(
	CashCode ASC,
	PaidOn ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Org_tbPayment_PaymentStatusCode ON Org.tbPayment
(
	PaymentStatusCode ASC,
	AccountCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Org_tbSector_IndustrySector ON Org.tbSector
(
	IndustrySector ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX RDX_Usr_tbMenuEntry_Command ON Usr.tbMenuEntry
(
	Command ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX RDX_Usr_tbMenuEntry_OpenMode ON Usr.tbMenuEntry
(
	OpenMode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX RDX_App_tbCalendarHoliday_CalendarCode ON App.tbCalendarHoliday
(
	CalendarCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX RDX_App_tbDocSpool_DocTypeCode ON App.tbDocSpool
(
	DocTypeCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_App_tbTaxCodeByType ON App.tbTaxCode
(
	TaxTypeCode ASC,
	TaxCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Task_tb_AccountCode ON Task.tbTask
(
	AccountCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Task_tb_AccountCodeByActionOn ON Task.tbTask
(
	AccountCode ASC,
	ActionOn ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Task_tb_AccountCodeByStatus ON Task.tbTask
(
	AccountCode ASC,
	TaskStatusCode ASC,
	ActionOn ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Task_tb_ActionBy ON Task.tbTask
(
	ActionById ASC,
	TaskStatusCode ASC,
	ActionOn ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Task_tb_ActionById ON Task.tbTask
(
	ActionById ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX IX_Task_tb_ActionOn ON Task.tbTask
(
	ActionOn DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Task_tb_ActionOnStatus ON Task.tbTask
(
	TaskStatusCode ASC,
	ActionOn ASC,
	AccountCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Task_tb_ActivityCode ON Task.tbTask
(
	ActivityCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Task_tb_ActivityCodeTaskTitle ON Task.tbTask
(
	ActivityCode ASC,
	TaskTitle ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Task_tb_ActivityStatusCode ON Task.tbTask
(
	TaskStatusCode ASC,
	ActionOn ASC,
	AccountCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Task_tb_CashCode ON Task.tbTask
(
	CashCode ASC,
	TaskStatusCode ASC,
	ActionOn ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX IX_Task_tb_TaskStatusCode ON Task.tbTask
(
	TaskStatusCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Task_tb_UserId ON Task.tbTask
(
	UserId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Task_tbAttribute ON Task.tbAttribute
(
	TaskCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Task_tbAttribute_Description ON Task.tbAttribute
(
	Attribute ASC,
	AttributeDescription ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Task_tbAttribute_OrderBy ON Task.tbAttribute
(
	TaskCode ASC,
	PrintOrder ASC,
	Attribute ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Task_tbAttribute_Type_OrderBy ON Task.tbAttribute
(
	TaskCode ASC,
	AttributeTypeCode ASC,
	PrintOrder ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE UNIQUE NONCLUSTERED INDEX IX_Task_tbFlow_ChildParent ON Task.tbFlow
(
	ChildTaskCode ASC,
	ParentTaskCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE UNIQUE NONCLUSTERED INDEX IX_Task_tbFlow_ParentChild ON Task.tbFlow
(
	ParentTaskCode ASC,
	ChildTaskCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX IX_Task_tbOp_OpStatusCode ON Task.tbOp
(
	OpStatusCode ASC,
	StartOn ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX IX_Task_tbOp_UserIdOpStatus ON Task.tbOp
(
	UserId ASC,
	OpStatusCode ASC,
	StartOn ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE UNIQUE NONCLUSTERED INDEX ActivityStatus ON Task.tbStatus
(
	TaskStatus ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE UNIQUE NONCLUSTERED INDEX IX_Usr_tb_LogonName ON Usr.tbUser
(
	LogonName ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE UNIQUE NONCLUSTERED INDEX UserName ON Usr.tbUser
(
	UserName ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
ALTER TABLE Activity.tbActivity ADD  CONSTRAINT DF_Activity_tbActivity_TaskStatusCode  DEFAULT (1) FOR TaskStatusCode
GO
ALTER TABLE Activity.tbActivity ADD  CONSTRAINT DF_Activity_tbActivity_UnitCharge  DEFAULT (0) FOR UnitCharge
GO
ALTER TABLE Activity.tbActivity ADD  CONSTRAINT DF_Activity_tbActivity_PrintOrder  DEFAULT (0) FOR PrintOrder
GO
ALTER TABLE Activity.tbActivity ADD  CONSTRAINT DF_Activity_tbActivity_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Activity.tbActivity ADD  CONSTRAINT DF_Activity_tbActivity_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Activity.tbActivity ADD  CONSTRAINT DF_Activity_tbActivity_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Activity.tbActivity ADD  CONSTRAINT DF_Activity_tbActivity_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Activity.tbAttribute ADD  CONSTRAINT DF_Activity_tbAttribute_OrderBy  DEFAULT (10) FOR PrintOrder
GO
ALTER TABLE Activity.tbAttribute ADD  CONSTRAINT DF_Activity_tbAttribute_AttributeTypeCode  DEFAULT (1) FOR AttributeTypeCode
GO
ALTER TABLE Activity.tbAttribute ADD  CONSTRAINT DF_tbTemplateAttribute_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Activity.tbAttribute ADD  CONSTRAINT DF_tbTemplateAttribute_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Activity.tbAttribute ADD  CONSTRAINT DF_tbTemplateAttribute_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Activity.tbAttribute ADD  CONSTRAINT DF_tbTemplateAttribute_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Activity.tbFlow ADD  CONSTRAINT DF_Activity_tbFlow_StepNumber  DEFAULT (10) FOR StepNumber
GO
ALTER TABLE Activity.tbFlow ADD  CONSTRAINT DF_Activity_tbFlow_OffsetDays  DEFAULT (0) FOR OffsetDays
GO
ALTER TABLE Activity.tbFlow ADD  CONSTRAINT DF_Activity_tbCodeFlow_Quantity  DEFAULT (0) FOR UsedOnQuantity
GO
ALTER TABLE Activity.tbFlow ADD  CONSTRAINT DF_tbTemplateActivity_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Activity.tbFlow ADD  CONSTRAINT DF_tbTemplateActivity_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Activity.tbFlow ADD  CONSTRAINT DF_tbTemplateActivity_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Activity.tbFlow ADD  CONSTRAINT DF_tbTemplateActivity_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Activity.tbOp ADD  CONSTRAINT DF_Activity_tbOp_OperationNumber  DEFAULT (0) FOR OperationNumber
GO
ALTER TABLE Activity.tbOp ADD  CONSTRAINT DF_Activity_tbOp_OpTypeCode  DEFAULT (1) FOR OpTypeCode
GO
ALTER TABLE Activity.tbOp ADD  CONSTRAINT DF_Activity_tbOp_Duration  DEFAULT (0) FOR Duration
GO
ALTER TABLE Activity.tbOp ADD  CONSTRAINT DF_Activity_tbOp_OffsetDays  DEFAULT (0) FOR OffsetDays
GO
ALTER TABLE Activity.tbOp ADD  CONSTRAINT DF_Activity_tbOp_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Activity.tbOp ADD  CONSTRAINT DF_Activity_tbOp_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Activity.tbOp ADD  CONSTRAINT DF_Activity_tbOp_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Activity.tbOp ADD  CONSTRAINT DF_Activity_tbOp_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Cash.tbCategory ADD  CONSTRAINT DF_Cash_tbCategory_CategoryTypeCode  DEFAULT (1) FOR CategoryTypeCode
GO
ALTER TABLE Cash.tbCategory ADD  CONSTRAINT DF_Cash_tbCategory_CashModeCode  DEFAULT (1) FOR CashModeCode
GO
ALTER TABLE Cash.tbCategory ADD  CONSTRAINT DF_Cash_tbCategory_CashTypeCode  DEFAULT (1) FOR CashTypeCode
GO
ALTER TABLE Cash.tbCategory ADD  CONSTRAINT DF_Cash_tbCategory_DisplayOrder  DEFAULT (0) FOR DisplayOrder
GO
ALTER TABLE Cash.tbCategory ADD  CONSTRAINT DF_Cash_tbCategory_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Cash.tbCategory ADD  CONSTRAINT DF_Cash_tbCategory_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Cash.tbCategory ADD  CONSTRAINT DF_Cash_tbCategory_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Cash.tbCategory ADD  CONSTRAINT DF_Cash_tbCategory_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Cash.tbCode ADD  CONSTRAINT DF_Cash_tbCode_OpeningBalance  DEFAULT (0) FOR OpeningBalance
GO
ALTER TABLE Cash.tbCode ADD  CONSTRAINT DF_Cash_tbCode_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Cash.tbCode ADD  CONSTRAINT DF_Cash_tbCode_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Cash.tbCode ADD  CONSTRAINT DF_Cash_tbCode_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Cash.tbCode ADD  CONSTRAINT DF_Cash_tbCode_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Cash.tbPeriod ADD  CONSTRAINT DF_Cash_tbPeriod_ForecastValue  DEFAULT (0) FOR ForecastValue
GO
ALTER TABLE Cash.tbPeriod ADD  CONSTRAINT DF_Cash_tbPeriod_ForecastTax  DEFAULT (0) FOR ForecastTax
GO
ALTER TABLE Cash.tbPeriod ADD  CONSTRAINT DF_Cash_tbPeriod_InvoiceValue  DEFAULT (0) FOR InvoiceValue
GO
ALTER TABLE Cash.tbPeriod ADD  CONSTRAINT DF_Cash_tbPeriod_InvoiceTax  DEFAULT (0) FOR InvoiceTax
GO
ALTER TABLE Cash.tbTaxType ADD  CONSTRAINT DF_App_tbOptions_MonthNumber  DEFAULT (1) FOR MonthNumber
GO
ALTER TABLE Cash.tbTaxType ADD  CONSTRAINT DF_App_tbOptions_Recurrence  DEFAULT (1) FOR RecurrenceCode
GO
ALTER TABLE Invoice.tbInvoice ADD  CONSTRAINT DF_Invoice_tb_InvoicedOn  DEFAULT (CONVERT(DATETIME,CONVERT(varchar,SYSDATETIME(),1),1)) FOR InvoicedOn
GO
ALTER TABLE Invoice.tbInvoice ADD  CONSTRAINT DF_Invoice_tb_InvoiceValue  DEFAULT (0) FOR InvoiceValue
GO
ALTER TABLE Invoice.tbInvoice ADD  CONSTRAINT DF_Invoice_tb_TaxValue  DEFAULT (0) FOR TaxValue
GO
ALTER TABLE Invoice.tbInvoice ADD  CONSTRAINT DF_Invoice_tb_PaidValue  DEFAULT (0) FOR PaidValue
GO
ALTER TABLE Invoice.tbInvoice ADD  CONSTRAINT DF_Invoice_tb_PaidTaxValue  DEFAULT (0) FOR PaidTaxValue
GO
ALTER TABLE Invoice.tbInvoice ADD  CONSTRAINT DF_Invoice_tb_Printed  DEFAULT (0) FOR Printed
GO
ALTER TABLE Invoice.tbInvoice ADD  CONSTRAINT DF_Invoice_tb_CollectOn  DEFAULT (SYSDATETIME()) FOR CollectOn
GO
ALTER TABLE Invoice.tbInvoice ADD  CONSTRAINT DF_Invoice_tb_Spooled  DEFAULT ((0)) FOR Spooled
GO
ALTER TABLE Invoice.tbItem ADD  CONSTRAINT DF_Invoice_tbItem_InvoiceValue  DEFAULT (0) FOR InvoiceValue
GO
ALTER TABLE Invoice.tbItem ADD  CONSTRAINT DF_Invoice_tbItem_TaxValue  DEFAULT (0) FOR TaxValue
GO
ALTER TABLE Invoice.tbItem ADD  CONSTRAINT DF_Invoice_tbItem_PaidValue  DEFAULT (0) FOR PaidValue
GO
ALTER TABLE Invoice.tbItem ADD  CONSTRAINT DF_Invoice_tbItem_PaidTaxValue  DEFAULT (0) FOR PaidTaxValue
GO
ALTER TABLE Invoice.tbTask ADD  CONSTRAINT DF_Invoice_tbTask_Quantity  DEFAULT (0) FOR Quantity
GO
ALTER TABLE Invoice.tbTask ADD  CONSTRAINT DF_Invoice_tbActivity_InvoiceValue  DEFAULT (0) FOR InvoiceValue
GO
ALTER TABLE Invoice.tbTask ADD  CONSTRAINT DF_Invoice_tbActivity_TaxValue  DEFAULT (0) FOR TaxValue
GO
ALTER TABLE Invoice.tbTask ADD  CONSTRAINT DF_Invoice_tbTask_PaidValue  DEFAULT (0) FOR PaidValue
GO
ALTER TABLE Invoice.tbTask ADD  CONSTRAINT DF_Invoice_tbTask_PaidTaxValue  DEFAULT (0) FOR PaidTaxValue
GO
ALTER TABLE Invoice.tbType ADD  CONSTRAINT DF_Invoice_tbType_NextNumber  DEFAULT (1000) FOR NextNumber
GO
ALTER TABLE Org.tbOrg ADD  CONSTRAINT DF_Org_tb_OrganisationTypeCode  DEFAULT (1) FOR OrganisationTypeCode
GO
ALTER TABLE Org.tbOrg ADD  CONSTRAINT DF_Org_tb_OrganisationStatusCode  DEFAULT (1) FOR OrganisationStatusCode
GO
ALTER TABLE Org.tbOrg ADD  CONSTRAINT DF_Org_tb_NumberOfEmployees  DEFAULT (0) FOR NumberOfEmployees
GO
ALTER TABLE Org.tbOrg ADD  CONSTRAINT DF_Org_tb_Turnover  DEFAULT (0) FOR Turnover
GO
ALTER TABLE Org.tbOrg ADD  CONSTRAINT DF_Org_tb_StatementDays  DEFAULT (365) FOR StatementDays
GO
ALTER TABLE Org.tbOrg ADD  CONSTRAINT DF_Org_tb_OpeningBalance  DEFAULT (0) FOR OpeningBalance
GO
ALTER TABLE Org.tbOrg ADD  CONSTRAINT DF_Org_tb_CurrentBalance  DEFAULT (0) FOR CurrentBalance
GO
ALTER TABLE Org.tbOrg ADD  CONSTRAINT DF_Org_tb_ForeignJurisdiction  DEFAULT (0) FOR ForeignJurisdiction
GO
ALTER TABLE Org.tbOrg ADD  CONSTRAINT DF_Org_tb_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Org.tbOrg ADD  CONSTRAINT DF_Org_tb_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Org.tbOrg ADD  CONSTRAINT DF_Org_tb_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Org.tbOrg ADD  CONSTRAINT DF_Org_tb_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Org.tbOrg ADD  CONSTRAINT DF_Org_tb_PaymentDays  DEFAULT (0) FOR PaymentDays
GO
ALTER TABLE Org.tbOrg ADD  CONSTRAINT DF_Org_tb_PayDaysFromMonthEnd  DEFAULT (0) FOR PayDaysFromMonthEnd
GO
ALTER TABLE Org.tbAccount ADD  CONSTRAINT DF_Org_tbAccount_OpeningBalance  DEFAULT (0) FOR OpeningBalance
GO
ALTER TABLE Org.tbAccount ADD  CONSTRAINT DF_Org_tbAccount_CurrentBalance  DEFAULT (0) FOR CurrentBalance
GO
ALTER TABLE Org.tbAccount ADD  CONSTRAINT DF_Org_tbAccount_AccountClosed  DEFAULT (0) FOR AccountClosed
GO
ALTER TABLE Org.tbAccount ADD  CONSTRAINT DF_Org_tbAccount_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Org.tbAccount ADD  CONSTRAINT DF_Org_tbAccount_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Org.tbAccount ADD  CONSTRAINT DF_Org_tbAccount_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Org.tbAccount ADD  CONSTRAINT DF_Org_tbAccount_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Org.tbAddress ADD  CONSTRAINT DF_Org_tbAddress_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Org.tbAddress ADD  CONSTRAINT DF_Org_tbAddress_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Org.tbAddress ADD  CONSTRAINT DF_Org_tbAddress_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Org.tbAddress ADD  CONSTRAINT DF_Org_tbAddress_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Org.tbContact ADD  CONSTRAINT DF_Org_tbContact_OnMailingList  DEFAULT (1) FOR OnMailingList
GO
ALTER TABLE Org.tbContact ADD  CONSTRAINT DF_Org_tbContact_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Org.tbContact ADD  CONSTRAINT DF_Org_tbContact_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Org.tbContact ADD  CONSTRAINT DF_Org_tbContact_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Org.tbContact ADD  CONSTRAINT DF_Org_tbContact_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Org.tbDoc ADD  CONSTRAINT DF_Org_tbDoc_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Org.tbDoc ADD  CONSTRAINT DF_Org_tbDoc_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Org.tbDoc ADD  CONSTRAINT DF_Org_tbDoc_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Org.tbDoc ADD  CONSTRAINT DF_Org_tbDoc_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Org.tbPayment ADD  CONSTRAINT DF_Org_tbPayment_PaymentStatusCode  DEFAULT (1) FOR PaymentStatusCode
GO
ALTER TABLE Org.tbPayment ADD  CONSTRAINT DF_Org_tbPayment_PaidOn  DEFAULT (CONVERT(DATETIME,CONVERT(varchar,SYSDATETIME(),1),1)) FOR PaidOn
GO
ALTER TABLE Org.tbPayment ADD  CONSTRAINT DF_Org_tbPayment_PaidInValue  DEFAULT (0) FOR PaidInValue
GO
ALTER TABLE Org.tbPayment ADD  CONSTRAINT DF_Org_tbPayment_PaidOutValue  DEFAULT (0) FOR PaidOutValue
GO
ALTER TABLE Org.tbPayment ADD  CONSTRAINT DF_Org_tbPayment_TaxInValue  DEFAULT (0) FOR TaxInValue
GO
ALTER TABLE Org.tbPayment ADD  CONSTRAINT DF_Org_tbPayment_TaxOutValue  DEFAULT (0) FOR TaxOutValue
GO
ALTER TABLE Org.tbPayment ADD  CONSTRAINT DF_Org_tbPayment_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Org.tbPayment ADD  CONSTRAINT DF_Org_tbPayment_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Org.tbPayment ADD  CONSTRAINT DF_Org_tbPayment_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Org.tbPayment ADD  CONSTRAINT DF_Org_tbPayment_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Org.tbStatus ADD  CONSTRAINT DF_Org_tbStatus_OrganisationStatusCode  DEFAULT (1) FOR OrganisationStatusCode
GO
ALTER TABLE Org.tbType ADD  CONSTRAINT DF_Org_tbType_OrganisationTypeCode  DEFAULT (1) FOR OrganisationTypeCode
GO
ALTER TABLE Usr.tbMenu ADD  CONSTRAINT DF_Usr_tbMenu_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Usr.tbMenu ADD  CONSTRAINT DF_Usr_tbMenu_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Usr.tbMenuCommand ADD  CONSTRAINT DF_Usr_tbMenuCommand_Command  DEFAULT (0) FOR Command
GO
ALTER TABLE Usr.tbMenuEntry ADD  CONSTRAINT DF_Usr_tbMenuEntry_MenuId  DEFAULT (0) FOR MenuId
GO
ALTER TABLE Usr.tbMenuEntry ADD  CONSTRAINT DF_Usr_tbMenuEntry_FolderId  DEFAULT (0) FOR FolderId
GO
ALTER TABLE Usr.tbMenuEntry ADD  CONSTRAINT DF_Usr_tbMenuEntry_ItemId  DEFAULT (0) FOR ItemId
GO
ALTER TABLE Usr.tbMenuEntry ADD  CONSTRAINT DF_Usr_tbMenuEntry_Command  DEFAULT (0) FOR Command
GO
ALTER TABLE Usr.tbMenuEntry ADD  CONSTRAINT DF_Usr_tbMenuEntry_OpenMode  DEFAULT (1) FOR OpenMode
GO
ALTER TABLE Usr.tbMenuEntry ADD  CONSTRAINT DF_Usr_tbMenuEntry_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Usr.tbMenuEntry ADD  CONSTRAINT DF_Usr_tbMenuEntry_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Usr.tbMenuEntry ADD  CONSTRAINT DF_Usr_tbMenuEntry_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Usr.tbMenuOpenMode ADD  CONSTRAINT DF_Usr_tbMenuOpenMode_OpenMode  DEFAULT (0) FOR OpenMode
GO
ALTER TABLE App.tbCalendar ADD  CONSTRAINT DF_App_tbCalendar_Monday  DEFAULT (1) FOR Monday
GO
ALTER TABLE App.tbCalendar ADD  CONSTRAINT DF_App_tbCalendar_Tuesday  DEFAULT (1) FOR Tuesday
GO
ALTER TABLE App.tbCalendar ADD  CONSTRAINT DF_App_tbCalendar_Wednesday  DEFAULT (1) FOR Wednesday
GO
ALTER TABLE App.tbCalendar ADD  CONSTRAINT DF_App_tbCalendar_Thursday  DEFAULT (1) FOR Thursday
GO
ALTER TABLE App.tbCalendar ADD  CONSTRAINT DF_App_tbCalendar_Friday  DEFAULT (1) FOR Friday
GO
ALTER TABLE App.tbCalendar ADD  CONSTRAINT DF_App_tbCalendar_Saturday  DEFAULT (0) FOR Saturday
GO
ALTER TABLE App.tbCalendar ADD  CONSTRAINT DF_App_tbCalendar_Sunday  DEFAULT (0) FOR Sunday
GO
ALTER TABLE App.tbDoc ADD  CONSTRAINT DF_App_tbDoc_OpenMode  DEFAULT (1) FOR OpenMode
GO
ALTER TABLE App.tbDocSpool ADD  CONSTRAINT DF_App_tbDocSpool_UserName  DEFAULT (SUSER_SNAME()) FOR UserName
GO
ALTER TABLE App.tbDocSpool ADD  CONSTRAINT DF_App_tbDocSpool_DocTypeCode  DEFAULT ((1)) FOR DocTypeCode
GO
ALTER TABLE App.tbDocSpool ADD  CONSTRAINT DF_App_tbDocSpool_SpooledOn  DEFAULT (SYSDATETIME()) FOR SpooledOn
GO
ALTER TABLE App.tbInstall ADD  CONSTRAINT DF_App_tbInstall_InstalledOn  DEFAULT (SYSDATETIME()) FOR InstalledOn
GO
ALTER TABLE App.tbInstall ADD  CONSTRAINT DF_App_tbInstall_InstalledBy  DEFAULT (SUSER_SNAME()) FOR InstalledBy
GO
ALTER TABLE App.tbInstall ADD  CONSTRAINT DF_App_tbInstall_CategoryId  DEFAULT (0) FOR CategoryId
GO
ALTER TABLE App.tbOptions ADD  CONSTRAINT DF_App_tbRoot_Initialised  DEFAULT (0) FOR Initialised
GO
ALTER TABLE App.tbOptions ADD  CONSTRAINT DF_App_tbRoot_SQLDataVersion  DEFAULT (1) FOR SQLDataVersion
GO
ALTER TABLE App.tbOptions ADD  CONSTRAINT DF_App_tbRoot_DefaultPrintMode  DEFAULT (2) FOR DefaultPrintMode
GO
ALTER TABLE App.tbOptions ADD  CONSTRAINT DF_App_tbOptions_BucketTypeCode  DEFAULT (1) FOR BucketTypeCode
GO
ALTER TABLE App.tbOptions ADD  CONSTRAINT DF_App_tbOptions_BucketIntervalCode  DEFAULT (1) FOR BucketIntervalCode
GO
ALTER TABLE App.tbOptions ADD  CONSTRAINT DF_App_tbOptions_ShowCashGraphs  DEFAULT (1) FOR ShowCashGraphs
GO
ALTER TABLE App.tbOptions ADD  CONSTRAINT DF_App_tbOptions_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE App.tbOptions ADD  CONSTRAINT DF_App_tbOptions_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE App.tbOptions ADD  CONSTRAINT DF_App_tbOptions_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE App.tbOptions ADD  CONSTRAINT DF_App_tbOptions_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE App.tbOptions ADD  CONSTRAINT DF_App_tbOptions_ScheduleOps  DEFAULT (1) FOR ScheduleOps
GO
ALTER TABLE App.tbOptions ADD  CONSTRAINT DF_App_tbOptions_TaxHorizon  DEFAULT (90) FOR TaxHorizon
GO
ALTER TABLE App.tbRegister ADD  CONSTRAINT DF_App_tbRegister_NextNumber  DEFAULT (1) FOR NextNumber
GO
ALTER TABLE App.tbTaxCode ADD  CONSTRAINT DF_App_tbVatCode_VatRate  DEFAULT (0) FOR TaxRate
GO
ALTER TABLE App.tbTaxCode ADD  CONSTRAINT DF_App_tbTaxCode_TaxTypeCode  DEFAULT (2) FOR TaxTypeCode
GO
ALTER TABLE App.tbTaxCode ADD  CONSTRAINT DF_App_tbTaxCode_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE App.tbTaxCode ADD  CONSTRAINT DF_App_tbTaxCode_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE App.tbYear ADD  CONSTRAINT DF_App_tbYear_StartMonth  DEFAULT (1) FOR StartMonth
GO
ALTER TABLE App.tbYear ADD  CONSTRAINT DF_App_tbYear_CashStatusCode  DEFAULT (1) FOR CashStatusCode
GO
ALTER TABLE App.tbYear ADD  CONSTRAINT DF_App_tbYear_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE App.tbYear ADD  CONSTRAINT DF_App_tbYear_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE App.tbYearPeriod ADD  CONSTRAINT DF_App_tbYearPeriod_CashStatusCode  DEFAULT (1) FOR CashStatusCode
GO
ALTER TABLE App.tbYearPeriod ADD  CONSTRAINT DF_App_tbYearPeriod_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE App.tbYearPeriod ADD  CONSTRAINT DF_App_tbYearPeriod_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE App.tbYearPeriod ADD  CONSTRAINT DF_App_tbYearPeriod_CorporationTaxRate  DEFAULT (0) FOR CorporationTaxRate
GO
ALTER TABLE App.tbYearPeriod ADD  CONSTRAINT DF_App_tbYearPeriod_TaxAdjustment  DEFAULT (0) FOR TaxAdjustment
GO
ALTER TABLE App.tbYearPeriod ADD  CONSTRAINT DF_App_tbYearPeriod_VatAdjustment  DEFAULT (0) FOR VatAdjustment
GO
ALTER TABLE Task.tbTask ADD  CONSTRAINT DF_Task_tbTask_ActionOn  DEFAULT (SYSDATETIME()) FOR ActionOn
GO
ALTER TABLE Task.tbTask ADD  CONSTRAINT DF_Task_tbTask_Quantity  DEFAULT (0) FOR Quantity
GO
ALTER TABLE Task.tbTask ADD  CONSTRAINT DF_Task_tb_UnitCharge  DEFAULT (0) FOR UnitCharge
GO
ALTER TABLE Task.tbTask ADD  CONSTRAINT DF_Task_tb_TotalCharge  DEFAULT (0) FOR TotalCharge
GO
ALTER TABLE Task.tbTask ADD  CONSTRAINT DF_Task_tb_Printed  DEFAULT (0) FOR Printed
GO
ALTER TABLE Task.tbTask ADD  CONSTRAINT DF_Task_tb_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Task.tbTask ADD  CONSTRAINT DF_Task_tb_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Task.tbTask ADD  CONSTRAINT DF_Task_tb_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Task.tbTask ADD  CONSTRAINT DF_Task_tb_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Task.tbTask ADD  CONSTRAINT DF_Task_tb_PaymentOn  DEFAULT (SYSDATETIME()) FOR PaymentOn
GO
ALTER TABLE Task.tbTask ADD  CONSTRAINT DF_Task_tb_Spooled  DEFAULT ((0)) FOR Spooled
GO
ALTER TABLE Task.tbAttribute ADD  CONSTRAINT DF_Task_tbAttribute_OrderBy  DEFAULT (10) FOR PrintOrder
GO
ALTER TABLE Task.tbAttribute ADD  CONSTRAINT DF_Task_tbAttribute_AttributeTypeCode  DEFAULT (1) FOR AttributeTypeCode
GO
ALTER TABLE Task.tbAttribute ADD  CONSTRAINT DF_tbJobAttribute_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Task.tbAttribute ADD  CONSTRAINT DF_tbJobAttribute_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Task.tbAttribute ADD  CONSTRAINT DF_tbJobAttribute_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Task.tbAttribute ADD  CONSTRAINT DF_tbJobAttribute_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Task.tbDoc ADD  CONSTRAINT DF_Task_tbDoc_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Task.tbDoc ADD  CONSTRAINT DF_Task_tbDoc_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Task.tbDoc ADD  CONSTRAINT DF_Task_tbDoc_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Task.tbDoc ADD  CONSTRAINT DF_Task_tbDoc_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Task.tbFlow ADD  CONSTRAINT DF_Task_tbFlow_StepNumber  DEFAULT (10) FOR StepNumber
GO
ALTER TABLE Task.tbFlow ADD  CONSTRAINT DF_Task_tbFlow_UsedOnQuantity  DEFAULT (1) FOR UsedOnQuantity
GO
ALTER TABLE Task.tbFlow ADD  CONSTRAINT DF_Task_tbFlow_OffsetDays  DEFAULT (0) FOR OffsetDays
GO
ALTER TABLE Task.tbFlow ADD  CONSTRAINT DF_Task_tbFlow_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Task.tbFlow ADD  CONSTRAINT DF_Task_tbFlow_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Task.tbFlow ADD  CONSTRAINT DF_Task_tbFlow_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Task.tbFlow ADD  CONSTRAINT DF_Task_tbFlow_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Task.tbOp ADD  CONSTRAINT DF_Task_tbOp_OpTypeCode  DEFAULT (1) FOR OpTypeCode
GO
ALTER TABLE Task.tbOp ADD  CONSTRAINT DF_Task_tbOp_OpStatusCode  DEFAULT (1) FOR OpStatusCode
GO
ALTER TABLE Task.tbOp ADD  CONSTRAINT DF_Task_tbOp_StartOn  DEFAULT (SYSDATETIME()) FOR StartOn
GO
ALTER TABLE Task.tbOp ADD  CONSTRAINT DF_Task_tbOp_EndOn  DEFAULT (SYSDATETIME()) FOR EndOn
GO
ALTER TABLE Task.tbOp ADD  CONSTRAINT DF_Task_tbOp_Duration  DEFAULT (0) FOR Duration
GO
ALTER TABLE Task.tbOp ADD  CONSTRAINT DF_Task_tbOp_OffsetDays  DEFAULT (0) FOR OffsetDays
GO
ALTER TABLE Task.tbOp ADD  CONSTRAINT DF_Task_tbOp_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Task.tbOp ADD  CONSTRAINT DF_Task_tbOp_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Task.tbOp ADD  CONSTRAINT DF_Task_tbOp_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Task.tbOp ADD  CONSTRAINT DF_Task_tbOp_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Task.tbQuote ADD  CONSTRAINT DF_Task_tbQuote_Quantity  DEFAULT (0) FOR Quantity
GO
ALTER TABLE Task.tbQuote ADD  CONSTRAINT DF_Task_tbQuote_TotalPrice  DEFAULT (0) FOR TotalPrice
GO
ALTER TABLE Task.tbQuote ADD  CONSTRAINT DF_Task_tbQuote_RunOnQuantity  DEFAULT (0) FOR RunOnQuantity
GO
ALTER TABLE Task.tbQuote ADD  CONSTRAINT DF_Task_tbQuote_RunOnPrice  DEFAULT (0) FOR RunOnPrice
GO
ALTER TABLE Task.tbQuote ADD  CONSTRAINT DF_Task_tbQuote_RunBackQuantity  DEFAULT (0) FOR RunBackQuantity
GO
ALTER TABLE Task.tbQuote ADD  CONSTRAINT DF_Task_tbQuote_RunBackPrice  DEFAULT (0) FOR RunBackPrice
GO
ALTER TABLE Task.tbQuote ADD  CONSTRAINT DF_Task_tbQuote_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Task.tbQuote ADD  CONSTRAINT DF_Task_tbQuote_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Task.tbQuote ADD  CONSTRAINT DF_Task_tbQuote_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Task.tbQuote ADD  CONSTRAINT DF_Task_tbQuote_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Usr.tbUser ADD  CONSTRAINT DF_Usr_tb_LogonName  DEFAULT (SUSER_SNAME()) FOR LogonName
GO
ALTER TABLE Usr.tbUser ADD  CONSTRAINT DF_Usr_tb_Administrator  DEFAULT (0) FOR Administrator
GO
ALTER TABLE Usr.tbUser ADD  CONSTRAINT DF_Usr_tb_InsertedBy  DEFAULT (SUSER_SNAME()) FOR InsertedBy
GO
ALTER TABLE Usr.tbUser ADD  CONSTRAINT DF_Usr_tb_InsertedOn  DEFAULT (SYSDATETIME()) FOR InsertedOn
GO
ALTER TABLE Usr.tbUser ADD  CONSTRAINT DF_Usr_tb_UpdatedBy  DEFAULT (SUSER_SNAME()) FOR UpdatedBy
GO
ALTER TABLE Usr.tbUser ADD  CONSTRAINT DF_Usr_tb_UpdatedOn  DEFAULT (SYSDATETIME()) FOR UpdatedOn
GO
ALTER TABLE Usr.tbUser ADD  CONSTRAINT DF_Usr_tb_NextTaskNumber  DEFAULT (1) FOR NextTaskNumber
GO
ALTER TABLE Activity.tbActivity  WITH CHECK ADD  CONSTRAINT FK_Activity_tbActivity_App_tbRegister FOREIGN KEY(RegisterName)
REFERENCES App.tbRegister (RegisterName)
ON UPDATE CASCADE
GO
ALTER TABLE Activity.tbActivity CHECK CONSTRAINT FK_Activity_tbActivity_App_tbRegister
GO
ALTER TABLE Activity.tbActivity  WITH CHECK ADD  CONSTRAINT FK_Activity_tbActivity_Cash_tbCode FOREIGN KEY(CashCode)
REFERENCES Cash.tbCode (CashCode)
ON UPDATE CASCADE
GO
ALTER TABLE Activity.tbActivity CHECK CONSTRAINT FK_Activity_tbActivity_Cash_tbCode
GO
ALTER TABLE Activity.tbActivity  WITH CHECK ADD  CONSTRAINT FK_Activity_tbActivity_App_tbUom FOREIGN KEY(UnitOfMeasure)
REFERENCES App.tbUom (UnitOfMeasure)
GO
ALTER TABLE Activity.tbActivity CHECK CONSTRAINT FK_Activity_tbActivity_App_tbUom
GO
ALTER TABLE Activity.tbAttribute  WITH CHECK ADD  CONSTRAINT FK_Activity_tbAttribute_tbActivity FOREIGN KEY(ActivityCode)
REFERENCES Activity.tbActivity (ActivityCode)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE Activity.tbAttribute CHECK CONSTRAINT FK_Activity_tbAttribute_tbActivity
GO
ALTER TABLE Activity.tbAttribute  WITH CHECK ADD  CONSTRAINT FK_Activity_tbAttribute_Activity_tbAttributeType FOREIGN KEY(AttributeTypeCode)
REFERENCES Activity.tbAttributeType (AttributeTypeCode)
GO
ALTER TABLE Activity.tbAttribute CHECK CONSTRAINT FK_Activity_tbAttribute_Activity_tbAttributeType
GO
ALTER TABLE Activity.tbFlow  WITH CHECK ADD  CONSTRAINT FK_Activity_tbFlow_tbActivityParent FOREIGN KEY(ParentCode)
REFERENCES Activity.tbActivity (ActivityCode)
GO
ALTER TABLE Activity.tbFlow CHECK CONSTRAINT FK_Activity_tbFlow_tbActivityParent
GO
ALTER TABLE Activity.tbFlow  WITH CHECK ADD  CONSTRAINT FK_Activity_tbFlow_Activity_tbChild FOREIGN KEY(ChildCode)
REFERENCES Activity.tbActivity (ActivityCode)
GO
ALTER TABLE Activity.tbFlow CHECK CONSTRAINT FK_Activity_tbFlow_Activity_tbChild
GO
ALTER TABLE Activity.tbOp  WITH CHECK ADD  CONSTRAINT FK_Activity_tbOp_tbActivity FOREIGN KEY(ActivityCode)
REFERENCES Activity.tbActivity (ActivityCode)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE Activity.tbOp CHECK CONSTRAINT FK_Activity_tbOp_tbActivity
GO
ALTER TABLE Activity.tbOp  WITH CHECK ADD  CONSTRAINT FK_Activity_tbOp_Activity_tbOpType FOREIGN KEY(OpTypeCode)
REFERENCES Activity.tbOpType (OpTypeCode)
GO
ALTER TABLE Activity.tbOp CHECK CONSTRAINT FK_Activity_tbOp_Activity_tbOpType
GO
ALTER TABLE Cash.tbCategory  WITH CHECK ADD  CONSTRAINT FK_Cash_tbCategory_Cash_tbCategoryType FOREIGN KEY(CategoryTypeCode)
REFERENCES Cash.tbCategoryType (CategoryTypeCode)
GO
ALTER TABLE Cash.tbCategory CHECK CONSTRAINT FK_Cash_tbCategory_Cash_tbCategoryType
GO
ALTER TABLE Cash.tbCategory  WITH CHECK ADD  CONSTRAINT FK_Cash_tbCategory_Cash_tbMode FOREIGN KEY(CashModeCode)
REFERENCES Cash.tbMode (CashModeCode)
GO
ALTER TABLE Cash.tbCategory CHECK CONSTRAINT FK_Cash_tbCategory_Cash_tbMode
GO
ALTER TABLE Cash.tbCategory  WITH CHECK ADD  CONSTRAINT FK_Cash_tbCategory_Cash_tbType FOREIGN KEY(CashTypeCode)
REFERENCES Cash.tbType (CashTypeCode)
GO
ALTER TABLE Cash.tbCategory CHECK CONSTRAINT FK_Cash_tbCategory_Cash_tbType
GO
ALTER TABLE Cash.tbCategoryExp  WITH CHECK ADD  CONSTRAINT FK_Cash_tbCategoryExp_Cash_tbCategory FOREIGN KEY(CategoryCode)
REFERENCES Cash.tbCategory (CategoryCode)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE Cash.tbCategoryExp CHECK CONSTRAINT FK_Cash_tbCategoryExp_Cash_tbCategory
GO
ALTER TABLE Cash.tbCategoryTotal  WITH CHECK ADD  CONSTRAINT FK_Cash_tbCategoryTotal_Cash_tbCategory_Parent FOREIGN KEY(ParentCode)
REFERENCES Cash.tbCategory (CategoryCode)
GO
ALTER TABLE Cash.tbCategoryTotal CHECK CONSTRAINT FK_Cash_tbCategoryTotal_Cash_tbCategory_Parent
GO
ALTER TABLE Cash.tbCategoryTotal  WITH CHECK ADD  CONSTRAINT FK_Cash_tbCategoryTotal_Cash_tbCategory_Child FOREIGN KEY(ChildCode)
REFERENCES Cash.tbCategory (CategoryCode)
GO
ALTER TABLE Cash.tbCategoryTotal CHECK CONSTRAINT FK_Cash_tbCategoryTotal_Cash_tbCategory_Child
GO
ALTER TABLE Cash.tbCode  WITH CHECK ADD  CONSTRAINT FK_Cash_tbCode_Cash_tbCategory1 FOREIGN KEY(CategoryCode)
REFERENCES Cash.tbCategory (CategoryCode)
ON UPDATE CASCADE
GO
ALTER TABLE Cash.tbCode CHECK CONSTRAINT FK_Cash_tbCode_Cash_tbCategory1
GO
ALTER TABLE Cash.tbCode  WITH NOCHECK ADD  CONSTRAINT FK_Cash_tbCode_App_tbTaxCode FOREIGN KEY(TaxCode)
REFERENCES App.tbTaxCode (TaxCode)
GO
ALTER TABLE Cash.tbCode CHECK CONSTRAINT FK_Cash_tbCode_App_tbTaxCode
GO
ALTER TABLE Cash.tbPeriod  WITH CHECK ADD  CONSTRAINT FK_Cash_tbPeriod_Cash_tbCode FOREIGN KEY(CashCode)
REFERENCES Cash.tbCode (CashCode)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE Cash.tbPeriod CHECK CONSTRAINT FK_Cash_tbPeriod_Cash_tbCode
GO
ALTER TABLE Cash.tbPeriod  WITH CHECK ADD  CONSTRAINT FK_Cash_tbPeriod_App_tbYearPeriod FOREIGN KEY(StartOn)
REFERENCES App.tbYearPeriod (StartOn)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE Cash.tbPeriod CHECK CONSTRAINT FK_Cash_tbPeriod_App_tbYearPeriod
GO
ALTER TABLE Cash.tbTaxType  WITH CHECK ADD  CONSTRAINT FK_Cash_tbTaxType_Cash_tbCode FOREIGN KEY(CashCode)
REFERENCES Cash.tbCode (CashCode)
GO
ALTER TABLE Cash.tbTaxType CHECK CONSTRAINT FK_Cash_tbTaxType_Cash_tbCode
GO
ALTER TABLE Cash.tbTaxType  WITH CHECK ADD  CONSTRAINT FK_Cash_tbTaxType_Org_tb FOREIGN KEY(AccountCode)
REFERENCES Org.tbOrg (AccountCode)
ON UPDATE CASCADE
GO
ALTER TABLE Cash.tbTaxType CHECK CONSTRAINT FK_Cash_tbTaxType_Org_tb
GO
ALTER TABLE Cash.tbTaxType  WITH CHECK ADD  CONSTRAINT FK_Cash_tbTaxType_Org_tbAccount FOREIGN KEY(CashAccountCode)
REFERENCES Org.tbAccount (CashAccountCode)
GO
ALTER TABLE Cash.tbTaxType CHECK CONSTRAINT FK_Cash_tbTaxType_Org_tbAccount
GO
ALTER TABLE Cash.tbTaxType  WITH CHECK ADD  CONSTRAINT FK_Cash_tbTaxType_App_tbMonth FOREIGN KEY(MonthNumber)
REFERENCES App.tbMonth (MonthNumber)
GO
ALTER TABLE Cash.tbTaxType CHECK CONSTRAINT FK_Cash_tbTaxType_App_tbMonth
GO
ALTER TABLE Cash.tbTaxType  WITH CHECK ADD  CONSTRAINT FK_Cash_tbTaxType_App_tbRecurrence FOREIGN KEY(RecurrenceCode)
REFERENCES App.tbRecurrence (RecurrenceCode)
GO
ALTER TABLE Cash.tbTaxType CHECK CONSTRAINT FK_Cash_tbTaxType_App_tbRecurrence
GO
ALTER TABLE Invoice.tbInvoice  WITH CHECK ADD  CONSTRAINT FK_Invoice_tb_Invoice_tbStatus FOREIGN KEY(InvoiceStatusCode)
REFERENCES Invoice.tbStatus (InvoiceStatusCode)
GO
ALTER TABLE Invoice.tbInvoice CHECK CONSTRAINT FK_Invoice_tb_Invoice_tbStatus
GO
ALTER TABLE Invoice.tbInvoice  WITH CHECK ADD  CONSTRAINT FK_Invoice_tb_Invoice_tbType FOREIGN KEY(InvoiceTypeCode)
REFERENCES Invoice.tbType (InvoiceTypeCode)
GO
ALTER TABLE Invoice.tbInvoice CHECK CONSTRAINT FK_Invoice_tb_Invoice_tbType
GO
ALTER TABLE Invoice.tbInvoice  WITH CHECK ADD  CONSTRAINT FK_Invoice_tb_Org_tb FOREIGN KEY(AccountCode)
REFERENCES Org.tbOrg (AccountCode)
GO
ALTER TABLE Invoice.tbInvoice CHECK CONSTRAINT FK_Invoice_tb_Org_tb
GO
ALTER TABLE Invoice.tbInvoice  WITH CHECK ADD  CONSTRAINT FK_Invoice_tb_Usr_tb FOREIGN KEY(UserId)
REFERENCES Usr.tbUser (UserId)
ON UPDATE CASCADE
GO
ALTER TABLE Invoice.tbInvoice CHECK CONSTRAINT FK_Invoice_tb_Usr_tb
GO
ALTER TABLE Invoice.tbItem  WITH CHECK ADD  CONSTRAINT FK_Invoice_tbItem_Cash_tbCode FOREIGN KEY(CashCode)
REFERENCES Cash.tbCode (CashCode)
ON UPDATE CASCADE
GO
ALTER TABLE Invoice.tbItem CHECK CONSTRAINT FK_Invoice_tbItem_Cash_tbCode
GO
ALTER TABLE Invoice.tbItem  WITH CHECK ADD  CONSTRAINT FK_Invoice_tbItem_Invoice_tb FOREIGN KEY(InvoiceNumber)
REFERENCES Invoice.tbInvoice (InvoiceNumber)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE Invoice.tbItem CHECK CONSTRAINT FK_Invoice_tbItem_Invoice_tb
GO
ALTER TABLE Invoice.tbItem  WITH NOCHECK ADD  CONSTRAINT FK_Invoice_tbItem_App_tbTaxCode FOREIGN KEY(TaxCode)
REFERENCES App.tbTaxCode (TaxCode)
GO
ALTER TABLE Invoice.tbItem CHECK CONSTRAINT FK_Invoice_tbItem_App_tbTaxCode
GO
ALTER TABLE Invoice.tbTask  WITH CHECK ADD  CONSTRAINT FK_Invoice_tbTask_Cash_tbCode FOREIGN KEY(CashCode)
REFERENCES Cash.tbCode (CashCode)
GO
ALTER TABLE Invoice.tbTask CHECK CONSTRAINT FK_Invoice_tbTask_Cash_tbCode
GO
ALTER TABLE Invoice.tbTask  WITH NOCHECK ADD  CONSTRAINT FK_Invoice_tbTask_App_tbTaxCode FOREIGN KEY(TaxCode)
REFERENCES App.tbTaxCode (TaxCode)
GO
ALTER TABLE Invoice.tbTask CHECK CONSTRAINT FK_Invoice_tbTask_App_tbTaxCode
GO
ALTER TABLE Invoice.tbTask  WITH CHECK ADD  CONSTRAINT FK_Invoice_tbTask_Invoice_tb FOREIGN KEY(InvoiceNumber)
REFERENCES Invoice.tbInvoice (InvoiceNumber)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE Invoice.tbTask CHECK CONSTRAINT FK_Invoice_tbTask_Invoice_tb
GO
ALTER TABLE Invoice.tbTask  WITH NOCHECK ADD  CONSTRAINT FK_Invoice_tbTask_Task_tb FOREIGN KEY(TaskCode)
REFERENCES Task.tbTask (TaskCode)
GO
ALTER TABLE Invoice.tbTask CHECK CONSTRAINT FK_Invoice_tbTask_Task_tb
GO
ALTER TABLE Invoice.tbType  WITH CHECK ADD  CONSTRAINT FK_Invoice_tbType_Cash_tbMode FOREIGN KEY(CashModeCode)
REFERENCES Cash.tbMode (CashModeCode)
GO
ALTER TABLE Invoice.tbType CHECK CONSTRAINT FK_Invoice_tbType_Cash_tbMode
GO
ALTER TABLE Org.tbOrg  WITH NOCHECK ADD  CONSTRAINT FK_Org_tb_Org_tbAddress FOREIGN KEY(AddressCode)
REFERENCES Org.tbAddress (AddressCode)
NOT FOR REPLICATION 
GO
ALTER TABLE Org.tbOrg NOCHECK CONSTRAINT FK_Org_tb_Org_tbAddress
GO
ALTER TABLE Org.tbOrg  WITH NOCHECK ADD  CONSTRAINT FK_Org_tb_App_tbTaxCode FOREIGN KEY(TaxCode)
REFERENCES App.tbTaxCode (TaxCode)
ON UPDATE CASCADE
GO
ALTER TABLE Org.tbOrg CHECK CONSTRAINT FK_Org_tb_App_tbTaxCode
GO
ALTER TABLE Org.tbOrg  WITH CHECK ADD  CONSTRAINT tbOrg_FK00 FOREIGN KEY(OrganisationStatusCode)
REFERENCES Org.tbStatus (OrganisationStatusCode)
GO
ALTER TABLE Org.tbOrg CHECK CONSTRAINT tbOrg_FK00
GO
ALTER TABLE Org.tbOrg  WITH CHECK ADD  CONSTRAINT tbOrg_FK01 FOREIGN KEY(OrganisationTypeCode)
REFERENCES Org.tbType (OrganisationTypeCode)
GO
ALTER TABLE Org.tbOrg CHECK CONSTRAINT tbOrg_FK01
GO
ALTER TABLE Org.tbAccount  WITH CHECK ADD  CONSTRAINT FK_Org_tbAccount_Cash_tbCode FOREIGN KEY(CashCode)
REFERENCES Cash.tbCode (CashCode)
GO
ALTER TABLE Org.tbAccount CHECK CONSTRAINT FK_Org_tbAccount_Cash_tbCode
GO
ALTER TABLE Org.tbAccount  WITH CHECK ADD  CONSTRAINT FK_Org_tbAccount_Org_tb FOREIGN KEY(AccountCode)
REFERENCES Org.tbOrg (AccountCode)
ON UPDATE CASCADE
GO
ALTER TABLE Org.tbAccount CHECK CONSTRAINT FK_Org_tbAccount_Org_tb
GO
ALTER TABLE Org.tbAddress  WITH CHECK ADD  CONSTRAINT FK_Org_tbAddress_Org_tb FOREIGN KEY(AccountCode)
REFERENCES Org.tbOrg (AccountCode)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE Org.tbAddress CHECK CONSTRAINT FK_Org_tbAddress_Org_tb
GO
ALTER TABLE Org.tbContact  WITH CHECK ADD  CONSTRAINT tbOrgContact_FK00 FOREIGN KEY(AccountCode)
REFERENCES Org.tbOrg (AccountCode)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE Org.tbContact CHECK CONSTRAINT tbOrgContact_FK00
GO
ALTER TABLE Org.tbDoc  WITH CHECK ADD  CONSTRAINT tbOrgDoc_FK00 FOREIGN KEY(AccountCode)
REFERENCES Org.tbOrg (AccountCode)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE Org.tbDoc CHECK CONSTRAINT tbOrgDoc_FK00
GO
ALTER TABLE Org.tbPayment  WITH CHECK ADD  CONSTRAINT FK_Org_tbPayment_Cash_tbCode FOREIGN KEY(CashCode)
REFERENCES Cash.tbCode (CashCode)
ON UPDATE CASCADE
GO
ALTER TABLE Org.tbPayment CHECK CONSTRAINT FK_Org_tbPayment_Cash_tbCode
GO
ALTER TABLE Org.tbPayment  WITH CHECK ADD  CONSTRAINT FK_Org_tbPayment_Org_tb FOREIGN KEY(AccountCode)
REFERENCES Org.tbOrg (AccountCode)
GO
ALTER TABLE Org.tbPayment CHECK CONSTRAINT FK_Org_tbPayment_Org_tb
GO
ALTER TABLE Org.tbPayment  WITH CHECK ADD  CONSTRAINT FK_Org_tbPayment_Org_tbAccount FOREIGN KEY(CashAccountCode)
REFERENCES Org.tbAccount (CashAccountCode)
ON UPDATE CASCADE
GO
ALTER TABLE Org.tbPayment CHECK CONSTRAINT FK_Org_tbPayment_Org_tbAccount
GO
ALTER TABLE Org.tbPayment  WITH CHECK ADD  CONSTRAINT FK_Org_tbPayment_Org_tbPaymentStatus FOREIGN KEY(PaymentStatusCode)
REFERENCES Org.tbPaymentStatus (PaymentStatusCode)
GO
ALTER TABLE Org.tbPayment CHECK CONSTRAINT FK_Org_tbPayment_Org_tbPaymentStatus
GO
ALTER TABLE Org.tbPayment  WITH NOCHECK ADD  CONSTRAINT FK_Org_tbPayment_App_tbTaxCode FOREIGN KEY(TaxCode)
REFERENCES App.tbTaxCode (TaxCode)
GO
ALTER TABLE Org.tbPayment CHECK CONSTRAINT FK_Org_tbPayment_App_tbTaxCode
GO
ALTER TABLE Org.tbPayment  WITH CHECK ADD  CONSTRAINT FK_Org_tbPayment_Usr_tb FOREIGN KEY(UserId)
REFERENCES Usr.tbUser (UserId)
ON UPDATE CASCADE
GO
ALTER TABLE Org.tbPayment CHECK CONSTRAINT FK_Org_tbPayment_Usr_tb
GO
ALTER TABLE Org.tbSector  WITH CHECK ADD  CONSTRAINT FK_Org_tbSector_Org_tb FOREIGN KEY(AccountCode)
REFERENCES Org.tbOrg (AccountCode)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE Org.tbSector CHECK CONSTRAINT FK_Org_tbSector_Org_tb
GO
ALTER TABLE Org.tbType  WITH CHECK ADD  CONSTRAINT FK_Org_tbType_Cash_tbMode FOREIGN KEY(CashModeCode)
REFERENCES Cash.tbMode (CashModeCode)
GO
ALTER TABLE Org.tbType CHECK CONSTRAINT FK_Org_tbType_Cash_tbMode
GO
ALTER TABLE Usr.tbMenuEntry  WITH CHECK ADD  CONSTRAINT FK_Usr_tbMenuEntry_Usr_tbMenu FOREIGN KEY(MenuId)
REFERENCES Usr.tbMenu (MenuId)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE Usr.tbMenuEntry CHECK CONSTRAINT FK_Usr_tbMenuEntry_Usr_tbMenu
GO
ALTER TABLE Usr.tbMenuEntry  WITH CHECK ADD  CONSTRAINT Usr_tbMenuEntry_FK01 FOREIGN KEY(Command)
REFERENCES Usr.tbMenuCommand (Command)
GO
ALTER TABLE Usr.tbMenuEntry CHECK CONSTRAINT Usr_tbMenuEntry_FK01
GO
ALTER TABLE Usr.tbMenuEntry  WITH CHECK ADD  CONSTRAINT Usr_tbMenuEntry_FK02 FOREIGN KEY(OpenMode)
REFERENCES Usr.tbMenuOpenMode (OpenMode)
GO
ALTER TABLE Usr.tbMenuEntry CHECK CONSTRAINT Usr_tbMenuEntry_FK02
GO
ALTER TABLE App.tbCalendarHoliday  WITH CHECK ADD  CONSTRAINT App_tbCalendarHoliday_FK00 FOREIGN KEY(CalendarCode)
REFERENCES App.tbCalendar (CalendarCode)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE App.tbCalendarHoliday CHECK CONSTRAINT App_tbCalendarHoliday_FK00
GO
ALTER TABLE App.tbDoc  WITH CHECK ADD  CONSTRAINT FK_App_tbDoc_Usr_tbMenuOpenMode FOREIGN KEY(OpenMode)
REFERENCES Usr.tbMenuOpenMode (OpenMode)
GO
ALTER TABLE App.tbDoc CHECK CONSTRAINT FK_App_tbDoc_Usr_tbMenuOpenMode
GO
ALTER TABLE App.tbDocSpool  WITH CHECK ADD  CONSTRAINT App_tbDocSpool_FK00 FOREIGN KEY(DocTypeCode)
REFERENCES App.tbDocType (DocTypeCode)
GO
ALTER TABLE App.tbDocSpool CHECK CONSTRAINT App_tbDocSpool_FK00
GO
ALTER TABLE App.tbOptions  WITH CHECK ADD  CONSTRAINT FK_App_tbOption_Cash_tbCategory FOREIGN KEY(NetProfitCode)
REFERENCES Cash.tbCategory (CategoryCode)
GO
ALTER TABLE App.tbOptions CHECK CONSTRAINT FK_App_tbOption_Cash_tbCategory
GO
ALTER TABLE App.tbOptions  WITH CHECK ADD  CONSTRAINT FK_App_tbOptions_App_tbBucketInterval FOREIGN KEY(BucketIntervalCode)
REFERENCES App.tbBucketInterval (BucketIntervalCode)
GO
ALTER TABLE App.tbOptions CHECK CONSTRAINT FK_App_tbOptions_App_tbBucketInterval
GO
ALTER TABLE App.tbOptions  WITH CHECK ADD  CONSTRAINT FK_App_tbOptions_App_tbBucketType FOREIGN KEY(BucketTypeCode)
REFERENCES App.tbBucketType (BucketTypeCode)
GO
ALTER TABLE App.tbOptions CHECK CONSTRAINT FK_App_tbOptions_App_tbBucketType
GO
ALTER TABLE App.tbOptions  WITH CHECK ADD  CONSTRAINT FK_App_tbRoot_Org_tb FOREIGN KEY(AccountCode)
REFERENCES Org.tbOrg (AccountCode)
ON UPDATE CASCADE
GO
ALTER TABLE App.tbOptions CHECK CONSTRAINT FK_App_tbRoot_Org_tb
GO
ALTER TABLE App.tbTaxCode  WITH NOCHECK ADD  CONSTRAINT FK_App_tbTaxCode_Cash_tbTaxType FOREIGN KEY(TaxTypeCode)
REFERENCES Cash.tbTaxType (TaxTypeCode)
GO
ALTER TABLE App.tbTaxCode CHECK CONSTRAINT FK_App_tbTaxCode_Cash_tbTaxType
GO
ALTER TABLE App.tbYear  WITH CHECK ADD  CONSTRAINT FK_App_tbYear_App_tbMonth FOREIGN KEY(StartMonth)
REFERENCES App.tbMonth (MonthNumber)
GO
ALTER TABLE App.tbYear CHECK CONSTRAINT FK_App_tbYear_App_tbMonth
GO
ALTER TABLE App.tbYearPeriod  WITH CHECK ADD  CONSTRAINT FK_App_tbYearPeriod_Cash_tbStatus FOREIGN KEY(CashStatusCode)
REFERENCES Cash.tbStatus (CashStatusCode)
GO
ALTER TABLE App.tbYearPeriod CHECK CONSTRAINT FK_App_tbYearPeriod_Cash_tbStatus
GO
ALTER TABLE App.tbYearPeriod  WITH CHECK ADD  CONSTRAINT FK_App_tbYearPeriod_App_tbMonth FOREIGN KEY(MonthNumber)
REFERENCES App.tbMonth (MonthNumber)
GO
ALTER TABLE App.tbYearPeriod CHECK CONSTRAINT FK_App_tbYearPeriod_App_tbMonth
GO
ALTER TABLE App.tbYearPeriod  WITH CHECK ADD  CONSTRAINT FK_App_tbYearPeriod_App_tbYear FOREIGN KEY(YearNumber)
REFERENCES App.tbYear (YearNumber)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE App.tbYearPeriod CHECK CONSTRAINT FK_App_tbYearPeriod_App_tbYear
GO
ALTER TABLE Task.tbTask  WITH NOCHECK ADD  CONSTRAINT FK_Task_tb_Cash_tbCode FOREIGN KEY(CashCode)
REFERENCES Cash.tbCode (CashCode)
GO
ALTER TABLE Task.tbTask CHECK CONSTRAINT FK_Task_tb_Cash_tbCode
GO
ALTER TABLE Task.tbTask  WITH NOCHECK ADD  CONSTRAINT FK_Task_tb_Org_tbAddress_From FOREIGN KEY(AddressCodeFrom)
REFERENCES Org.tbAddress (AddressCode)
GO
ALTER TABLE Task.tbTask CHECK CONSTRAINT FK_Task_tb_Org_tbAddress_From
GO
ALTER TABLE Task.tbTask  WITH NOCHECK ADD  CONSTRAINT FK_Task_tb_Org_tbAddress_To FOREIGN KEY(AddressCodeTo)
REFERENCES Org.tbAddress (AddressCode)
GO
ALTER TABLE Task.tbTask CHECK CONSTRAINT FK_Task_tb_Org_tbAddress_To
GO
ALTER TABLE Task.tbTask  WITH NOCHECK ADD  CONSTRAINT FK_Task_tb_App_tbTaxCode FOREIGN KEY(TaxCode)
REFERENCES App.tbTaxCode (TaxCode)
GO
ALTER TABLE Task.tbTask CHECK CONSTRAINT FK_Task_tb_App_tbTaxCode
GO
ALTER TABLE Task.tbTask  WITH NOCHECK ADD  CONSTRAINT FK_Task_tb_Usr_tb FOREIGN KEY(UserId)
REFERENCES Usr.tbUser (UserId)
ON UPDATE CASCADE
GO
ALTER TABLE Task.tbTask CHECK CONSTRAINT FK_Task_tb_Usr_tb
GO
ALTER TABLE Task.tbTask  WITH NOCHECK ADD  CONSTRAINT FK_Task_tb_Usr_tb_ActionById FOREIGN KEY(ActionById)
REFERENCES Usr.tbUser (UserId)
GO
ALTER TABLE Task.tbTask CHECK CONSTRAINT FK_Task_tb_Usr_tb_ActionById
GO
ALTER TABLE Task.tbTask  WITH NOCHECK ADD  CONSTRAINT Activity_tb_FK00 FOREIGN KEY(ActivityCode)
REFERENCES Activity.tbActivity (ActivityCode)
ON UPDATE CASCADE
GO
ALTER TABLE Task.tbTask CHECK CONSTRAINT Activity_tb_FK00
GO
ALTER TABLE Task.tbTask  WITH NOCHECK ADD  CONSTRAINT Activity_tb_FK01 FOREIGN KEY(TaskStatusCode)
REFERENCES Task.tbStatus (TaskStatusCode)
GO
ALTER TABLE Task.tbTask CHECK CONSTRAINT Activity_tb_FK01
GO
ALTER TABLE Task.tbTask  WITH NOCHECK ADD  CONSTRAINT Activity_tb_FK02 FOREIGN KEY(AccountCode)
REFERENCES Org.tbOrg (AccountCode)
ON UPDATE CASCADE
GO
ALTER TABLE Task.tbTask CHECK CONSTRAINT Activity_tb_FK02
GO
ALTER TABLE Task.tbAttribute  WITH NOCHECK ADD  CONSTRAINT FK_Task_tbAttrib_Task_tb FOREIGN KEY(TaskCode)
REFERENCES Task.tbTask (TaskCode)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE Task.tbAttribute CHECK CONSTRAINT FK_Task_tbAttrib_Task_tb
GO
ALTER TABLE Task.tbAttribute  WITH CHECK ADD  CONSTRAINT FK_Task_tbAttribute_Activity_tbAttributeType FOREIGN KEY(AttributeTypeCode)
REFERENCES Activity.tbAttributeType (AttributeTypeCode)
GO
ALTER TABLE Task.tbAttribute CHECK CONSTRAINT FK_Task_tbAttribute_Activity_tbAttributeType
GO
ALTER TABLE Task.tbDoc  WITH NOCHECK ADD  CONSTRAINT FK_Task_tbDoc_Task_tb FOREIGN KEY(TaskCode)
REFERENCES Task.tbTask (TaskCode)
GO
ALTER TABLE Task.tbDoc CHECK CONSTRAINT FK_Task_tbDoc_Task_tb
GO
ALTER TABLE Task.tbFlow  WITH NOCHECK ADD  CONSTRAINT FK_Task_tbFlow_Task_tb_Parent FOREIGN KEY(ParentTaskCode)
REFERENCES Task.tbTask (TaskCode)
GO
ALTER TABLE Task.tbFlow CHECK CONSTRAINT FK_Task_tbFlow_Task_tb_Parent
GO
ALTER TABLE Task.tbFlow  WITH NOCHECK ADD  CONSTRAINT FK_Task_tbFlow_Task_tb_Child FOREIGN KEY(ChildTaskCode)
REFERENCES Task.tbTask (TaskCode)
GO
ALTER TABLE Task.tbFlow CHECK CONSTRAINT FK_Task_tbFlow_Task_tb_Child
GO
ALTER TABLE Task.tbOp  WITH CHECK ADD  CONSTRAINT FK_Task_tbOp_Activity_tbOpType FOREIGN KEY(OpTypeCode)
REFERENCES Activity.tbOpType (OpTypeCode)
GO
ALTER TABLE Task.tbOp CHECK CONSTRAINT FK_Task_tbOp_Activity_tbOpType
GO
ALTER TABLE Task.tbOp  WITH NOCHECK ADD  CONSTRAINT FK_Task_tbOp_Task_tb FOREIGN KEY(TaskCode)
REFERENCES Task.tbTask (TaskCode)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE Task.tbOp CHECK CONSTRAINT FK_Task_tbOp_Task_tb
GO
ALTER TABLE Task.tbOp  WITH CHECK ADD  CONSTRAINT FK_Task_tbOp_Task_tbOpStatus FOREIGN KEY(OpStatusCode)
REFERENCES Task.tbOpStatus (OpStatusCode)
GO
ALTER TABLE Task.tbOp CHECK CONSTRAINT FK_Task_tbOp_Task_tbOpStatus
GO
ALTER TABLE Task.tbOp  WITH CHECK ADD  CONSTRAINT FK_Task_tbOp_Usr_tb FOREIGN KEY(UserId)
REFERENCES Usr.tbUser (UserId)
GO
ALTER TABLE Task.tbOp CHECK CONSTRAINT FK_Task_tbOp_Usr_tb
GO
ALTER TABLE Task.tbQuote  WITH NOCHECK ADD  CONSTRAINT FK_Task_tbQuote_Task_tb FOREIGN KEY(TaskCode)
REFERENCES Task.tbTask (TaskCode)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE Task.tbQuote CHECK CONSTRAINT FK_Task_tbQuote_Task_tb
GO
ALTER TABLE Usr.tbUser  WITH CHECK ADD  CONSTRAINT FK_Usr_tb_App_tbCalendar FOREIGN KEY(CalendarCode)
REFERENCES App.tbCalendar (CalendarCode)
ON UPDATE CASCADE
GO
ALTER TABLE Usr.tbUser CHECK CONSTRAINT FK_Usr_tb_App_tbCalendar
GO
ALTER TABLE Usr.tbMenuUser  WITH CHECK ADD  CONSTRAINT FK_Usr_tbMenu_Usr_tbMenu FOREIGN KEY(MenuId)
REFERENCES Usr.tbMenu (MenuId)
GO
ALTER TABLE Usr.tbMenuUser CHECK CONSTRAINT FK_Usr_tbMenu_Usr_tbMenu
GO
ALTER TABLE Usr.tbMenuUser  WITH CHECK ADD  CONSTRAINT FK_Usr_tbMenu_Usr_tb FOREIGN KEY(UserId)
REFERENCES Usr.tbUser (UserId)
ON UPDATE CASCADE
GO
ALTER TABLE Usr.tbMenuUser CHECK CONSTRAINT FK_Usr_tbMenu_Usr_tb
GO
