CREATE SCHEMA [Activity]
GO
CREATE SCHEMA [App]
GO
CREATE SCHEMA [Cash]
GO
CREATE SCHEMA [Invoice]
GO
CREATE SCHEMA [Org]
GO
CREATE SCHEMA [Task]
GO
CREATE SCHEMA [Usr]
GO


GO

GO
CREATE TABLE Activity.tbActivity(
	ActivityCode NVARCHAR(50) NOT NULL,
	TaskStatusCode SMALLINT NOT NULL,
	DefaultText ntext NULL,
	UnitOfMeasure NVARCHAR(15) NOT NULL,
	CashCode NVARCHAR(50) NULL,
	UnitCharge money NOT NULL,
	PrintOrder bit NOT NULL,
	RegisterName NVARCHAR(50) NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
 CONSTRAINT aaaaatbActivityCode_PK PRIMARY KEY NONCLUSTERED 
(
	ActivityCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

GO

GO
CREATE TABLE Activity.tbAttribute(
	ActivityCode NVARCHAR(50) NOT NULL,
	Attribute NVARCHAR(50) NOT NULL,
	PrintOrder SMALLINT NOT NULL,
	AttributeTypeCode SMALLINT NOT NULL,
	DefaultText NVARCHAR(400) NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
 CONSTRAINT PK_Activity_tbCodeAttrib PRIMARY KEY CLUSTERED 
(
	ActivityCode ASC,
	Attribute ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Activity.tbAttributeType(
	AttributeTypeCode SMALLINT NOT NULL,
	AttributeType NVARCHAR(20) NOT NULL,
 CONSTRAINT PK_Activity_tbAttributeType PRIMARY KEY CLUSTERED 
(
	AttributeTypeCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Activity.tbFlow(
	ParentCode NVARCHAR(50) NOT NULL,
	StepNumber SMALLINT NOT NULL,
	ChildCode NVARCHAR(50) NOT NULL,
	OffsetDays SMALLINT NOT NULL,
	UsedOnQuantity float NOT NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
 CONSTRAINT aaaaatbActivityCodeFlow_PK PRIMARY KEY NONCLUSTERED 
(
	ParentCode ASC,
	StepNumber ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Activity.tbOp(
	ActivityCode NVARCHAR(50) NOT NULL,
	OperationNumber SMALLINT NOT NULL,
	OpTypeCode SMALLINT NOT NULL,
	Operation NVARCHAR(50) NOT NULL,
	Duration float NOT NULL,
	OffsetDays SMALLINT NOT NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
 CONSTRAINT PK_Activity_tbOp PRIMARY KEY CLUSTERED 
(
	ActivityCode ASC,
	OperationNumber ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Activity.tbOpType(
	OpTypeCode SMALLINT NOT NULL,
	OpType NVARCHAR(50) NOT NULL,
 CONSTRAINT PK_Activity_tbOpType PRIMARY KEY CLUSTERED 
(
	OpTypeCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Cash.tbCategory(
	CategoryCode NVARCHAR(10) NOT NULL,
	Category NVARCHAR(50) NOT NULL,
	CategoryTypeCode SMALLINT NOT NULL,
	CashModeCode SMALLINT NULL,
	CashTypeCode SMALLINT NULL,
	DisplayOrder SMALLINT NOT NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
 CONSTRAINT PK_Cash_tbCategory PRIMARY KEY CLUSTERED 
(
	CategoryCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Cash.tbCategoryExp(
	CategoryCode NVARCHAR(10) NOT NULL,
	Expression NVARCHAR(256) NOT NULL,
	Format NVARCHAR(100) NOT NULL,
 CONSTRAINT PK_Cash_tbCategoryExp PRIMARY KEY CLUSTERED 
(
	CategoryCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Cash.tbCategoryTotal(
	ParentCode NVARCHAR(10) NOT NULL,
	ChildCode NVARCHAR(10) NOT NULL,
 CONSTRAINT PK_Cash_tbCategoryTotal PRIMARY KEY CLUSTERED 
(
	ParentCode ASC,
	ChildCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Cash.tbCategoryType(
	CategoryTypeCode SMALLINT NOT NULL,
	CategoryType NVARCHAR(20) NOT NULL,
 CONSTRAINT PK_Cash_tbCategoryType PRIMARY KEY CLUSTERED 
(
	CategoryTypeCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Cash.tbCode(
	CashCode NVARCHAR(50) NOT NULL,
	CashDescription NVARCHAR(100) NOT NULL,
	CategoryCode NVARCHAR(10) NOT NULL,
	TaxCode NVARCHAR(10) NOT NULL,
	OpeningBalance money NOT NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
 CONSTRAINT PK_Cash_tbCode PRIMARY KEY CLUSTERED 
(
	CashCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT IX_Cash_tbCodeDescription UNIQUE NONCLUSTERED 
(
	CashDescription ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Cash.tbEntryType(
	CashEntryTypeCode SMALLINT NOT NULL,
	CashEntryType NVARCHAR(20) NOT NULL,
 CONSTRAINT PK_Cash_tbEntryType PRIMARY KEY CLUSTERED 
(
	CashEntryTypeCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Cash.tbMode(
	CashModeCode SMALLINT NOT NULL,
	CashMode NVARCHAR(10) NULL,
 CONSTRAINT PK_Cash_tbMode PRIMARY KEY CLUSTERED 
(
	CashModeCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Cash.tbPeriod(
	CashCode NVARCHAR(50) NOT NULL,
	StartOn date NOT NULL,
	ForecastValue money NOT NULL,
	ForecastTax money NOT NULL,
	InvoiceValue money NOT NULL,
	InvoiceTax money NOT NULL,
	Note ntext NULL,
 CONSTRAINT PK_Cash_tbPeriod PRIMARY KEY CLUSTERED 
(
	CashCode ASC,
	StartOn ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

GO

GO
CREATE TABLE Cash.tbStatus(
	CashStatusCode SMALLINT NOT NULL,
	CashStatus NVARCHAR(15) NOT NULL,
 CONSTRAINT PK_Cash_tbStatus PRIMARY KEY CLUSTERED 
(
	CashStatusCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Cash.tbTaxType(
	TaxTypeCode SMALLINT NOT NULL,
	TaxType NVARCHAR(20) NOT NULL,
	CashCode NVARCHAR(50) NULL,
	MonthNumber SMALLINT NOT NULL,
	RecurrenceCode SMALLINT NOT NULL,
	AccountCode NVARCHAR(10) NULL,
	CashAccountCode NVARCHAR(10) NULL,
 CONSTRAINT PK_Cash_tbTaxType PRIMARY KEY CLUSTERED 
(
	TaxTypeCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Cash.tbType(
	CashTypeCode SMALLINT NOT NULL,
	CashType NVARCHAR(25) NULL,
 CONSTRAINT PK_Cash_tbType PRIMARY KEY CLUSTERED 
(
	CashTypeCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Invoice.tbInvoice(
	InvoiceNumber NVARCHAR(20) NOT NULL,
	UserId NVARCHAR(10) NOT NULL,
	AccountCode NVARCHAR(10) NOT NULL,
	InvoiceTypeCode SMALLINT NOT NULL,
	InvoiceStatusCode SMALLINT NOT NULL,
	InvoicedOn date NOT NULL,
	InvoiceValue money NOT NULL,
	TaxValue money NOT NULL,
	PaidValue money NOT NULL,
	PaidTaxValue money NOT NULL,
	PaymentTerms NVARCHAR(100) NULL,
	Notes ntext NULL,
	Printed bit NOT NULL,
	CollectOn datetime NOT NULL,
	Spooled bit NOT NULL,
 CONSTRAINT PK_Invoice_tb PRIMARY KEY CLUSTERED 
(
	InvoiceNumber ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

GO

GO
CREATE TABLE Invoice.tbItem(
	InvoiceNumber NVARCHAR(20) NOT NULL,
	CashCode NVARCHAR(50) NOT NULL,
	TaxCode NVARCHAR(10) NULL,
	InvoiceValue money NOT NULL,
	TaxValue money NOT NULL,
	PaidValue money NOT NULL,
	PaidTaxValue money NOT NULL,
	ItemReference ntext NULL,
 CONSTRAINT PK_Invoice_tbItem PRIMARY KEY CLUSTERED 
(
	InvoiceNumber ASC,
	CashCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

GO

GO
CREATE TABLE Invoice.tbStatus(
	InvoiceStatusCode SMALLINT NOT NULL,
	InvoiceStatus NVARCHAR(50) NULL,
 CONSTRAINT aaaaatbInvoiceStatus_PK PRIMARY KEY NONCLUSTERED 
(
	InvoiceStatusCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Invoice.tbTask(
	InvoiceNumber NVARCHAR(20) NOT NULL,
	TaskCode NVARCHAR(20) NOT NULL,
	Quantity float NOT NULL,
	InvoiceValue money NOT NULL,
	TaxValue money NOT NULL,
	PaidValue money NOT NULL,
	PaidTaxValue money NOT NULL,
	CashCode NVARCHAR(50) NOT NULL,
	TaxCode NVARCHAR(10) NULL,
 CONSTRAINT PK_Invoice_tbTask PRIMARY KEY CLUSTERED 
(
	InvoiceNumber ASC,
	TaskCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Invoice.tbType(
	InvoiceTypeCode SMALLINT NOT NULL,
	InvoiceType NVARCHAR(20) NOT NULL,
	CashModeCode SMALLINT NOT NULL,
	NextNumber int NOT NULL,
 CONSTRAINT PK_Invoice_tbType PRIMARY KEY CLUSTERED 
(
	InvoiceTypeCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Org.tbOrg(
	AccountCode NVARCHAR(10) NOT NULL,
	AccountName NVARCHAR(255) NOT NULL,
	OrganisationTypeCode SMALLINT NOT NULL,
	OrganisationStatusCode SMALLINT NOT NULL,
	TaxCode NVARCHAR(10) NULL,
	AddressCode NVARCHAR(15) NULL,
	AreaCode NVARCHAR(50) NULL,
	PhoneNumber NVARCHAR(50) NULL,
	FaxNumber NVARCHAR(50) NULL,
	EmailAddress NVARCHAR(255) NULL,
	WebSite NVARCHAR(255) NULL,
	IndustrySector NVARCHAR(255) NULL,
	AccountSource NVARCHAR(100) NULL,
	PaymentTerms NVARCHAR(100) NULL,
	NumberOfEmployees int NOT NULL,
	CompanyNumber NVARCHAR(20) NULL,
	VatNumber NVARCHAR(50) NULL,
	Turnover money NOT NULL,
	StatementDays SMALLINT NOT NULL,
	OpeningBalance money NOT NULL,
	CurrentBalance money NOT NULL,
	ForeignJurisdiction bit NOT NULL,
	BusinessDescription ntext NULL,
	Logo image NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
	PaymentDays SMALLINT NOT NULL,
	PayDaysFromMonthEnd bit NOT NULL,
 CONSTRAINT aaaaatbOrg_PK PRIMARY KEY NONCLUSTERED 
(
	AccountCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

GO

GO
CREATE TABLE Org.tbAccount(
	CashAccountCode NVARCHAR(10) NOT NULL,
	AccountCode NVARCHAR(10) NOT NULL,
	CashAccountName NVARCHAR(50) NOT NULL,
	OpeningBalance money NOT NULL,
	CurrentBalance money NOT NULL,
	SortCode NVARCHAR(10) NULL,
	AccountNumber NVARCHAR(20) NULL,
	CashCode NVARCHAR(50) NULL,
	AccountClosed bit NOT NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
 CONSTRAINT PK_Org_tbAccount PRIMARY KEY CLUSTERED 
(
	CashAccountCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Org.tbAddress(
	AddressCode NVARCHAR(15) NOT NULL,
	AccountCode NVARCHAR(10) NOT NULL,
	Address ntext NOT NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
 CONSTRAINT PK_Org_tbAddress PRIMARY KEY CLUSTERED 
(
	AddressCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

GO

GO
CREATE TABLE Org.tbContact(
	AccountCode NVARCHAR(10) NOT NULL,
	ContactName NVARCHAR(100) NOT NULL,
	FileAs NVARCHAR(100) NULL,
	OnMailingList bit NOT NULL,
	NameTitle NVARCHAR(25) NULL,
	NickName NVARCHAR(100) NULL,
	JobTitle NVARCHAR(100) NULL,
	Department NVARCHAR(50) NULL,
	PhoneNumber NVARCHAR(50) NULL,
	MobileNumber NVARCHAR(50) NULL,
	FaxNumber NVARCHAR(50) NULL,
	EmailAddress NVARCHAR(255) NULL,
	Hobby NVARCHAR(50) NULL,
	DateOfBirth datetime NULL,
	HomeNumber NVARCHAR(50) NULL,
	SpouseName NVARCHAR(50) NULL,
	Information ntext NULL,
	Photo image NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
 CONSTRAINT aaaaatbOrgContact_PK PRIMARY KEY NONCLUSTERED 
(
	AccountCode ASC,
	ContactName ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

GO

GO
CREATE TABLE Org.tbDoc(
	AccountCode NVARCHAR(10) NOT NULL,
	DocumentName NVARCHAR(255) NOT NULL,
	DocumentDescription ntext NULL,
	DocumentImage image NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
 CONSTRAINT aaaaatbOrgDoc_PK PRIMARY KEY NONCLUSTERED 
(
	AccountCode ASC,
	DocumentName ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

GO

GO
CREATE TABLE Org.tbPayment(
	PaymentCode NVARCHAR(20) NOT NULL,
	UserId NVARCHAR(10) NOT NULL,
	PaymentStatusCode SMALLINT NOT NULL,
	AccountCode NVARCHAR(10) NOT NULL,
	CashAccountCode NVARCHAR(10) NOT NULL,
	CashCode NVARCHAR(50) NULL,
	TaxCode NVARCHAR(10) NULL,
	PaidOn datetime NOT NULL,
	PaidInValue money NOT NULL,
	PaidOutValue money NOT NULL,
	TaxInValue money NOT NULL,
	TaxOutValue money NOT NULL,
	PaymentReference NVARCHAR(50) NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
 CONSTRAINT PK_Org_tbPayment PRIMARY KEY CLUSTERED 
(
	PaymentCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Org.tbPaymentStatus(
	PaymentStatusCode SMALLINT NOT NULL,
	PaymentStatus NVARCHAR(20) NOT NULL,
 CONSTRAINT PK_Org_tbPaymentStatus PRIMARY KEY CLUSTERED 
(
	PaymentStatusCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Org.tbSector(
	AccountCode NVARCHAR(10) NOT NULL,
	IndustrySector NVARCHAR(50) NOT NULL,
 CONSTRAINT PK_Org_tbSector PRIMARY KEY CLUSTERED 
(
	AccountCode ASC,
	IndustrySector ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Org.tbStatus(
	OrganisationStatusCode SMALLINT NOT NULL,
	OrganisationStatus NVARCHAR(255) NULL,
 CONSTRAINT aaaaatbOrgStatus_PK PRIMARY KEY NONCLUSTERED 
(
	OrganisationStatusCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Org.tbType(
	OrganisationTypeCode SMALLINT NOT NULL,
	CashModeCode SMALLINT NOT NULL,
	OrganisationType NVARCHAR(50) NOT NULL,
 CONSTRAINT aaaaatbOrgType_PK PRIMARY KEY NONCLUSTERED 
(
	OrganisationTypeCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Usr.tbMenu(
	MenuId SMALLINT IDENTITY(1,1) NOT NULL,
	MenuName NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
 CONSTRAINT PK_Usr_tbMenu PRIMARY KEY CLUSTERED 
(
	MenuId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT IX_Usr_tbMenu UNIQUE NONCLUSTERED 
(
	MenuName ASC,
	MenuId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Usr.tbMenuCommand(
	Command SMALLINT NOT NULL,
	CommandText NVARCHAR(50) NULL,
 CONSTRAINT PK_Usr_tbMenuCommand PRIMARY KEY CLUSTERED 
(
	Command ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Usr.tbMenuEntry(
	MenuId SMALLINT NOT NULL,
	EntryId int IDENTITY(1,1) NOT NULL,
	FolderId SMALLINT NOT NULL,
	ItemId SMALLINT NOT NULL,
	ItemText NVARCHAR(255) NULL,
	Command SMALLINT NULL,
	ProjectName NVARCHAR(50) NULL,
	Argument NVARCHAR(50) NULL,
	OpenMode SMALLINT NULL,
	UpdatedOn datetime NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
 CONSTRAINT PK_Usr_tbMenuEntry PRIMARY KEY CLUSTERED 
(
	MenuId ASC,
	EntryId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT IX_Usr_tbMenuEntry_MenuFolderItem UNIQUE NONCLUSTERED 
(
	MenuId ASC,
	FolderId ASC,
	ItemId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Usr.tbMenuOpenMode(
	OpenMode SMALLINT NOT NULL,
	OpenModeDescription NVARCHAR(20) NULL,
 CONSTRAINT PK_Usr_tbMenuOpenMode PRIMARY KEY CLUSTERED 
(
	OpenMode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE App.tbText(
	TextId int NOT NULL,
	Message ntext NOT NULL,
	Arguments SMALLINT NOT NULL,
 CONSTRAINT PK_App_tbText PRIMARY KEY CLUSTERED 
(
	TextId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

GO

GO
CREATE TABLE App.tbBucket(
	Period SMALLINT NOT NULL,
	BucketId NVARCHAR(10) NOT NULL,
	BucketDescription NVARCHAR(50) NULL,
	AllowForecasts bit NOT NULL,
 CONSTRAINT PK_App_tbBucket PRIMARY KEY CLUSTERED 
(
	Period ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE App.tbBucketInterval(
	BucketIntervalCode SMALLINT NOT NULL,
	BucketInterval NVARCHAR(15) NOT NULL,
 CONSTRAINT PK_App_tbBucketInterval PRIMARY KEY CLUSTERED 
(
	BucketIntervalCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE App.tbBucketType(
	BucketTypeCode SMALLINT NOT NULL,
	BucketType NVARCHAR(25) NOT NULL,
 CONSTRAINT PK_App_tbBucketType PRIMARY KEY CLUSTERED 
(
	BucketTypeCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE App.tbCalendar(
	CalendarCode NVARCHAR(10) NOT NULL,
	Monday bit NOT NULL,
	Tuesday bit NOT NULL,
	Wednesday bit NOT NULL,
	Thursday bit NOT NULL,
	Friday bit NOT NULL,
	Saturday bit NOT NULL,
	Sunday bit NOT NULL,
 CONSTRAINT PK_App_tbCalendar PRIMARY KEY CLUSTERED 
(
	CalendarCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE App.tbCalendarHoliday(
	CalendarCode NVARCHAR(10) NOT NULL,
	UnavailableOn date NOT NULL,
 CONSTRAINT PK_App_tbCalendarHoliday PRIMARY KEY CLUSTERED 
(
	CalendarCode ASC,
	UnavailableOn ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE App.tbCodeExclusion(
	ExcludedTag NVARCHAR(100) NOT NULL,
 CONSTRAINT PK_App_tbCodeExclusion PRIMARY KEY CLUSTERED 
(
	ExcludedTag ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE App.tbDoc(
	DocTypeCode SMALLINT NOT NULL,
	ReportName NVARCHAR(50) NOT NULL,
	OpenMode SMALLINT NOT NULL,
	Description NVARCHAR(50) NOT NULL,
 CONSTRAINT PK_App_tbDoc PRIMARY KEY CLUSTERED 
(
	DocTypeCode ASC,
	ReportName ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE App.tbDocSpool(
	UserName NVARCHAR(50) NOT NULL,
	DocTypeCode SMALLINT NOT NULL,
	DocumentNumber NVARCHAR(25) NOT NULL,
	SpooledOn datetime NOT NULL,
 CONSTRAINT PK_App_tbDocSpool PRIMARY KEY CLUSTERED 
(
	UserName ASC,
	DocTypeCode ASC,
	DocumentNumber ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE App.tbDocType(
	DocTypeCode SMALLINT NOT NULL,
	DocType NVARCHAR(50) NOT NULL,
 CONSTRAINT PK_App_tbDocType PRIMARY KEY CLUSTERED 
(
	DocTypeCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE App.tbInstall(
	InstallId int IDENTITY(1,1) NOT NULL,
	InstalledOn datetime NOT NULL,
	InstalledBy NVARCHAR(50) NOT NULL,
	DataVersion float NOT NULL,
	CategoryId SMALLINT NOT NULL,
	CategoryTypeCode SMALLINT NOT NULL,
	ReleaseTypeCode SMALLINT NOT NULL,
	Licence binary(50) NULL,
	LicenceType SMALLINT NULL,
 CONSTRAINT PK_App_tbInstall PRIMARY KEY CLUSTERED 
(
	InstallId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE App.tbMonth(
	MonthNumber SMALLINT NOT NULL,
	MonthName NVARCHAR(10) NOT NULL,
 CONSTRAINT PK_App_tbMonth PRIMARY KEY CLUSTERED 
(
	MonthNumber ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE App.tbOptions(
	Identifier NVARCHAR(4) NOT NULL,
	Initialised bit NOT NULL,
	SQLDataVersion real NOT NULL,
	AccountCode NVARCHAR(10) NOT NULL,
	DefaultPrintMode SMALLINT NOT NULL,
	BucketTypeCode SMALLINT NOT NULL,
	BucketIntervalCode SMALLINT NOT NULL,
	ShowCashGraphs bit NOT NULL,
	NetProfitCode NVARCHAR(10) NULL,
	NetProfitTaxCode NVARCHAR(50) NULL,
	ScheduleOps bit NOT NULL,
	TaxHorizon SMALLINT NOT NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
CONSTRAINT PK_App_tbRoot PRIMARY KEY CLUSTERED 
(
	Identifier ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE App.tbRecurrence(
	RecurrenceCode SMALLINT NOT NULL,
	Recurrence NVARCHAR(20) NOT NULL,
 CONSTRAINT PK_App_tbRecurrence PRIMARY KEY CLUSTERED 
(
	RecurrenceCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE App.tbRegister(
	RegisterName NVARCHAR(50) NOT NULL,
	NextNumber int NOT NULL,
 CONSTRAINT PK_App_tbRegister PRIMARY KEY CLUSTERED 
(
	RegisterName ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE App.tbTaxCode(
	TaxCode NVARCHAR(10) NOT NULL,
	TaxRate float NOT NULL,
	TaxDescription NVARCHAR(50) NOT NULL,
	TaxTypeCode SMALLINT NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
 CONSTRAINT PK_App_tbVatCode PRIMARY KEY CLUSTERED 
(
	TaxCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE App.tbUom(
	UnitOfMeasure NVARCHAR(15) NOT NULL,
 CONSTRAINT PK_App_tbUom PRIMARY KEY CLUSTERED 
(
	UnitOfMeasure ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE App.tbYear(
	YearNumber SMALLINT NOT NULL,
	StartMonth SMALLINT NOT NULL,
	CashStatusCode SMALLINT NOT NULL,
	Description NVARCHAR(10) NOT NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
 CONSTRAINT PK_App_tbYear PRIMARY KEY CLUSTERED 
(
	YearNumber ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE App.tbYearPeriod(
	YearNumber SMALLINT NOT NULL,
	StartOn date NOT NULL,
	MonthNumber SMALLINT NOT NULL,
	CashStatusCode SMALLINT NOT NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	CorporationTaxRate real NOT NULL,
	TaxAdjustment money NOT NULL,
	VatAdjustment money NOT NULL,
 CONSTRAINT PK_App_tbYearPeriod PRIMARY KEY CLUSTERED 
(
	YearNumber ASC,
	StartOn ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT IX_App_tbYearPeriod_StartOn UNIQUE NONCLUSTERED 
(
	StartOn ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT IX_App_tbYearPeriod_Year_MonthNumber UNIQUE NONCLUSTERED 
(
	YearNumber ASC,
	MonthNumber ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Task.tbTask(
	TaskCode NVARCHAR(20) NOT NULL,
	UserId NVARCHAR(10) NOT NULL,
	AccountCode NVARCHAR(10) NOT NULL,
	TaskTitle NVARCHAR(100) NULL,
	ContactName NVARCHAR(100) NULL,
	ActivityCode NVARCHAR(50) NOT NULL,
	TaskStatusCode SMALLINT NOT NULL,
	ActionById NVARCHAR(10) NOT NULL,
	ActionOn date NOT NULL,
	ActionedOn datetime NULL,
	TaskNotes NVARCHAR(255) NULL,
	Quantity float NOT NULL,
	CashCode NVARCHAR(50) NULL,
	TaxCode NVARCHAR(10) NULL,
	UnitCharge float NOT NULL,
	TotalCharge money NOT NULL,
	AddressCodeFrom NVARCHAR(15) NULL,
	AddressCodeTo NVARCHAR(15) NULL,
	Printed bit NOT NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
	PaymentOn datetime NOT NULL,
	SecondReference NVARCHAR(20) NULL,
	Spooled bit NOT NULL,
 CONSTRAINT PK_Task_tb PRIMARY KEY CLUSTERED 
(
	TaskCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Task.tbAttribute(
	TaskCode NVARCHAR(20) NOT NULL,
	Attribute NVARCHAR(50) NOT NULL,
	PrintOrder SMALLINT NOT NULL,
	AttributeTypeCode SMALLINT NOT NULL,
	AttributeDescription NVARCHAR(400) NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
 CONSTRAINT PK_Task_tbTaskAttribute PRIMARY KEY CLUSTERED 
(
	TaskCode ASC,
	Attribute ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Task.tbDoc(
	TaskCode NVARCHAR(20) NOT NULL,
	DocumentName NVARCHAR(255) NOT NULL,
	DocumentDescription ntext NULL,
	DocumentImage image NOT NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
 CONSTRAINT PK_Task_tbDoc PRIMARY KEY CLUSTERED 
(
	TaskCode ASC,
	DocumentName ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

GO

GO
CREATE TABLE Task.tbFlow(
	ParentTaskCode NVARCHAR(20) NOT NULL,
	StepNumber SMALLINT NOT NULL,
	ChildTaskCode NVARCHAR(20) NULL,
	UsedOnQuantity float NOT NULL,
	OffsetDays real NOT NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
 CONSTRAINT PK_Task_tbFlow PRIMARY KEY CLUSTERED 
(
	ParentTaskCode ASC,
	StepNumber ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Task.tbOp(
	TaskCode NVARCHAR(20) NOT NULL,
	OperationNumber SMALLINT NOT NULL,
	OpTypeCode SMALLINT NOT NULL,
	OpStatusCode SMALLINT NOT NULL,
	UserId NVARCHAR(10) NOT NULL,
	Operation NVARCHAR(50) NOT NULL,
	Note ntext NULL,
	StartOn date NOT NULL,
	EndOn date NOT NULL,
	Duration float NOT NULL,
	OffsetDays SMALLINT NOT NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
 CONSTRAINT PK_Task_tbOp PRIMARY KEY CLUSTERED 
(
	TaskCode ASC,
	OperationNumber ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

GO

GO
CREATE TABLE Task.tbOpStatus(
	OpStatusCode SMALLINT NOT NULL,
	OpStatus NVARCHAR(50) NOT NULL,
 CONSTRAINT PK_Task_tbOpStatus PRIMARY KEY CLUSTERED 
(
	OpStatusCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Task.tbQuote(
	TaskCode NVARCHAR(20) NOT NULL,
	Quantity float NOT NULL,
	TotalPrice money NOT NULL,
	RunOnQuantity float NOT NULL,
	RunOnPrice money NOT NULL,
	RunBackQuantity float NOT NULL,
	RunBackPrice float NOT NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
 CONSTRAINT PK_Task_tbQuote PRIMARY KEY CLUSTERED 
(
	TaskCode ASC,
	Quantity ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Task.tbStatus(
	TaskStatusCode SMALLINT NOT NULL,
	TaskStatus NVARCHAR(100) NOT NULL,
 CONSTRAINT aaaaatbActivityStatus_PK PRIMARY KEY NONCLUSTERED 
(
	TaskStatusCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

GO
CREATE TABLE Usr.tbUser(
	UserId NVARCHAR(10) NOT NULL,
	UserName NVARCHAR(50) NOT NULL,
	LogonName NVARCHAR(50) NOT NULL,
	CalendarCode NVARCHAR(10) NULL,
	PhoneNumber NVARCHAR(50) NULL,
	MobileNumber NVARCHAR(50) NULL,
	FaxNumber NVARCHAR(50) NULL,
	EmailAddress NVARCHAR(255) NULL,
	Address ntext NULL,
	Administrator bit NOT NULL,
	Avatar image NULL,
	Signature image NULL,
	InsertedBy NVARCHAR(50) NOT NULL,
	InsertedOn datetime NOT NULL,
	UpdatedBy NVARCHAR(50) NOT NULL,
	UpdatedOn datetime NOT NULL,
	NextTaskNumber int NOT NULL,
 CONSTRAINT PK_Usr_tb PRIMARY KEY CLUSTERED 
(
	UserId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

GO

GO
CREATE TABLE Usr.tbMenuUser(
	UserId NVARCHAR(10) NOT NULL,
	MenuId SMALLINT NOT NULL,
 CONSTRAINT PK_Usr_tbMenuUser PRIMARY KEY CLUSTERED 
(
	UserId ASC,
	MenuId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO
